### ISSUE TITLE
Does not seem to make Overwatch any smoother

### ISSUE THREAD

**Issue by SpectralMemories** [rcpoison/dxvk-cache-pool#13]
Hi!
I am probably doing something wrong here but I'll ask anyway.
I installed the package on Arch via makepkg -fsric (using the provided PKGBUILD file), ran dxvk_cache_pool_client /home/alex/.wine (my only wineprefix, where Overwatch is installed), The log seemed to indicate that it worked. If I re-run the command, it gives

> [alex@alex-PC]:home/alex dxvk-cache-client /home/alex/.wine/
> target directory is: /home/alex/.cache/dxvk-cache-pool
> scanning directories
>  scanned 4780 files
> preparing wine prefixes
> looking up remote caches for 89 possible games
>  found 2 matching caches
> writing 0 new caches
> updating 2 caches
>  Overwatch: signing 1674 locally built entries
>  Overwatch: sending 1674 locally built entries to remote
>  Overwatch: is up to date (21704 entries)
>  Battle.net: is up to date (46 entries)
> found 0 candidates for upload
> [alex@alex-PC]:home/alex

The PKGBUILD successfuly made the env variable, as proven by:

> 
> [alex@alex-PC]:home/alex echo $DXVK_STATE_CACHE_PATH
> /home/alex/.cache/dxvk-cache-pool
> [alex@alex-PC]:home/alex 

The symlink exists:

> [alex@alex-PC]:home/alex/.wine/drive_c ls -l
> total 20
> lrwxrwxrwx  1 alex alex   33 Oct 15 20:15  dxvk-cache-pool -> /home/alex/.cache/dxvk-cache-pool
> drwxr-xr-x  6 alex alex 4096 Oct  8 12:13  ProgramData
> drwxr-xr-x  6 alex alex 4096 Oct  8 11:55 'Program Files'
> drwxr-xr-x  8 alex alex 4096 Oct  8 12:14 'Program Files (x86)'
> drwxr-xr-x  4 alex alex 4096 Oct  8 11:55  users
> drwxr-xr-x 19 alex alex 4096 Oct  8 11:58  windows
> [alex@alex-PC]:home/alex/.wine/drive_c

And the overwatch entry is in the directory:

> [alex@alex-PC]:/home/alex/.cache/dxvk-cache-pool ls -l
> total 38748
> -rw-r--r-- 1 alex alex    83916 Oct 15 20:15 Battle.net.dxvk-cache
> -rw-r--r-- 1 alex alex 39588108 Oct 15 20:35 Overwatch.dxvk-cache
> [alex@alex-PC]:home/alex/.cache/dxvk-cache-pool

I rebooted, and the game is still very much stuttery and does not seem to use the completed cache at all. I can tell that caching is enabled tho, as spells stop lagging after repeated uses. Did I do something wrong? Thanks anyone for insights!

**Comment by SpectralMemories** [comment]
Damn the formatting sucks here

**Comment by SpectralMemories** [comment]
Just realised that the cache in your remote has yet to be completed. Upside is: I am contributing to it :D

**Comment by rcpoison** [comment]
@SpectralMemories You can change the required signatures to 1 if you don't care much for security and just want all of the cache. The overwatch cache is already large but there aren't many contributors so the signature requirements aren't met yet.

**Comment by rcpoison** [comment]
for my own reference:
```
Overwatch: 64712 entries
signatureCount: 0, occurences: 97
signatureCount: 1, occurences: 41170
signatureCount: 2, occurences: 23440
signatureCount: 3, occurences: 5
```
