### ISSUE TITLE
Question: Does dxvk-cache-pool merge the cache files?

### ISSUE THREAD

**Issue by Zeioth** [rcpoison/dxvk-cache-pool#14]
Let's imagine an example:

- We have N clients playing Quake Champions.
- After playing, every player upload his state cache file to the dxvk-cache-pool server.

My question is: What state cache file is the one that prevalis on the server? The biggest one? Or all state caches are merged into a single file?

**Comment by rcpoison** [comment]
The cache file is split into it's individual entries.
The server deals with cache entries as does the client.
https://github.com/rcpoison/dxvk-cache-pool/blob/master/dxvk-cache-pool-common/src/main/java/com/ignorelist/kassandra/dxvk/cache/pool/common/StateCacheIO.java

**Comment by rcpoison** [comment]
Yes, the server has all the entries, just not as a single file. The client does the merging.

I've already opened a ticket on the lutris project and got the response that they're not happy with java ;)

Lutris would just use it like any other CLI program. They could easily make it an optional dependency so they really wouldn't have to care about the language.
