### ISSUE TITLE
Ubuntu / Debian package

### ISSUE THREAD

**Issue by rcpoison** [rcpoison/dxvk-cache-pool#3]
Most popular distribution, should probably provide packages for easy access

**Comment by SpectralMemories** [comment]
Being rather bored tonight I created a first prototype. I tested it in an Ubuntu 18.04 virtual machine. I included one package that includes openjdk-8-jre as a dependency, and another one that does not (for custom java implementations). All the informations provided in the deb file should be reviewed, including the man page I came up with. [Enjoy!](https://drive.google.com/file/d/1Itw6ynJHEc3NMGbtc0oAGITIWrhl8G-7/view?usp=sharing)

[Screenshot](https://imgur.com/a/qxbP7YV)

**Comment by rcpoison** [comment]
@SpectralMemories: That's awesome, thank you! I'll look at it after work :)

**Comment by rcpoison** [comment]
Wow, you even went to the trouble of creating a manpage :)

Looks good to me!

How would you go about including the package sources in the git project?
Does debians packaging system support pulling sources from git?
Or should I write a build script for debian that copies everything to the expected place in the package source dir?

**Comment by rcpoison** [comment]
@SpectralMemories I've managed building the package automatically.

Do you midn if I pilfer your manpage? :)

**Comment by SpectralMemories** [comment]
@rcpoison Use the manpage as you please, else I would have written it for nothing haha :)
