### ISSUE TITLE
Add an option to only update caches already inside DXVK_STATE_CACHE_PATH or specified directory

### ISSUE THREAD

**Issue by Sporif** [rcpoison/dxvk-cache-pool#5]
I'd like an option to make `dxvk-state-cache` use only the cache files already present in `DXVK_STATE_CACHE_PATH` and update those. Either though a parameter or the default behaviour if a directory is not specified or if a non-wineprefix path is specified. Something like this:

```
DXVK_STATE_CACHE_PATH=~/dxvk-state-cache dxvk-cache-client
scanning directories
no directory specified
using DXVK_STATE_CACHE_PATH
found 3 caches
updating 2 caches
...
```

or

```
./dxvk-cache-client ~/dxvk-state-cache
scanning directories
not a wineprefix, treating as cache directory
found 3 caches
updating 2 caches
...
```

**Comment by rcpoison** [comment]
@Sporif I've added
```
--cache-target-dir <dir>   Override default cache target directory
```
in the develop branch.
Without specifying additional paths to scan it will only scan the target dir.

Could you please explain why your games aren't in your wine prefixes? Are you using some kind of tool/wine frontend?
I'd like to understand if this is something common.

**Comment by Sporif** [comment]
I have two wine prefixes, one for Origin and one for Battle.net. All my games are not installed in the default libraries which are inside the wine prefixes, but rather on separate drives. This way I can recreate wine prefixes at any time and instead of re-downloading the games simply re-import the libraries.

A way around this I suppose is you can add an option to specify game libraries as well.

**Comment by rcpoison** [comment]
@Sporif: thanks for elaborating.

> A way around this I suppose is you can add an option to specify game libraries as well.

That's already possible. I'm just figuring out the wineprefixes in order to create symlinks inside of them to the shared cache in case they are sandboxed and z: is not available. 
So strictly speaking the passed directories do not have to be wine prefixes.

**Comment by tgharib** [comment]
I'm confused. Why does the dxvk-cache-pool client need to know about the wine prefixes anyway? If it is aware of the directory where the dxvk state caches are stored, doesn't it only need to download missing entries and uploading new entries?

**Comment by rcpoison** [comment]
@tgharib : 
- To scan for executables which have a matching cache on the remote. So caches can be downloaded before the game is even run for the first time.
- Like already mentioned, to create symlinks inside of the prefixes to the cache directory. If the wine prefix is sandboxed wine cannot access anything outside of it and hence setting the dxvk cache dir to something outside of the wine prefix will not work.

(Thanks for your pull request, I can really use help with user documentation, I'm not good at that. I'm too tired right now but I'll look at it tomorrow)
